// ignore_for_file: file_names, non_constant_identifier_names

final Map<String, String> en_US = {
  // Common
  'hello': 'Hello',
  'welcome': 'Welcome to our app!',
  'continue': 'Continue',
  'cancel': 'Cancel',
  'save': 'Save',
  'delete': 'Delete',
  'edit': 'Edit',
  'done': 'Done',
  'loading': 'Loading...',
  'error': 'Error',
  'success': 'Success',
  'retry': 'Retry',
  'or': 'OR',
  'of': 'of',
  'version': 'Version',
  
  // Authentication
  'login': 'Login',
  'signin': 'Sign In',
  'signup': 'Sign Up',
  'register': 'Register',
  'logout': 'Logout',
  'signOut': 'Sign Out',
  'email': 'Email',
  'emailAddress': 'Email Address',
  'password': 'Password',
  'newPassword': 'New Password',
  'confirmPassword': 'Confirm Password',
  'confirmNewPassword': 'Confirm New Password',
  'forgotPassword': 'Forgot Password?',
  'resetPassword': 'Reset Password',
  'updatePassword': 'Update Password',
  'enterEmail': 'Enter your email',
  'enterEmailAddress': 'Enter your email address',
  'enterPassword': 'Enter your password',
  'enterCredentialsMessage': 'Enter your credentials to access your account',
  'fillDetailsMessage': 'Fill in your details to get started',
  'rememberMe': 'Remember me',
  'createAccount': 'Create Account',
  'createNewPassword': 'Create New Password',
  'newPasswordDifferentMessage': 'Your new password must be different from previous passwords',
  'setNewPassword': 'Set New Password',
  'createStrongPasswordMessage': 'Create a strong password to secure your account',
  'alreadyHaveAccount': 'Already have an account?',
  'dontHaveAccount': "Don't have an account?",
  'sendResetLink': 'Send Reset Link',
  'resetPasswordMessage': "Enter your email and we'll send you a link to reset your password",
  'noWorriesResetMessage': "No worries, we'll send you reset instructions",
  'cantFindEmailMessage': "Can't find the email? Check your spam folder or try again with a different email address.",
  'continueToSignIn': 'Continue to Sign In',
  
  // Password Requirements
  'passwordRequirements': 'Password Requirements',
  'atLeast8Chars': 'At least 8 characters',
  'oneUppercase': 'One uppercase letter',
  'oneLowercase': 'One lowercase letter',
  'oneNumber': 'One number',
  'passwordUpdated': 'Password Updated!',
  'passwordUpdatedMessage': 'Your password has been successfully updated. You can now sign in with your new password.',
  
  // OTP Verification
  'recoveryEmail': 'Recovery Email',
  'checkYourEmail': 'Check Your Email',
  'verificationCodeSentMessage': "We've sent a verification code to your email",
  'enterVerificationCode': 'Enter Verification Code',
  'weSent6DigitCode': 'We sent a 6-digit code to',
  'verifyCode': 'Verify Code',
  'didntReceiveCode': "Didn't receive the code?",
  'didntReceiveCodeMessage': "Didn't receive the code? Check your spam folder or request a new one.",
  'resend': 'Resend',
  'resendIn': 'Resend in',
  'enterValid6DigitCode': 'Please enter a valid 6-digit code',
  
  // Profile & Settings
  'profile': 'Profile',
  'editProfile': 'Edit Profile',
  'updatePersonalInfo': 'Update your personal information',
  'settings': 'Settings',
  'account': 'Account',
  'personalInfo': 'Personal Information',
  'firstName': 'First Name',
  'lastName': 'Last Name',
  'fullName': 'Full Name',
  'phoneNumber': 'Phone Number',
  'notifications': 'Notifications',
  'pushNotifications': 'Push notifications',
  'smsNotifications': 'SMS Notifications',
  'darkMode': 'Dark Mode',
  'language': 'Language',
  'current': 'Current:',
  'selectLanguage': 'Select Language',
  'english': 'English',
  'french': 'Français',
  'analytics': 'Analytics',
  'helpImproveApp': 'Help improve the app',
  'rateApp': 'Rate App',
  'contactSupport': 'Contact Support',
  'privacyPolicy': 'Privacy Policy',
  'support': 'Support',
  'memberSince': 'Member since',
  'signOutConfirmation': 'Are you sure you want to sign out?',
  'signedOutSuccess': 'You have been signed out successfully',
  
  // Navigation
  'home': 'Home',
  'dashboard': 'Dashboard',
  'progress': 'Progress',
  'back': 'Back',
  'next': 'Next',
  
  // Home Screen
  'welcomeHome': 'Welcome Home',
  'availableBalance': 'Available balance',
  'quickActions': 'QUICK ACTIONS',
  'newTransfer': 'New transfer',
  'enterTransferDetails': 'Please enter transfer details.',
  'validate': 'Validate',
  'payByCard': 'Pay by card',
  'supermarket': 'Supermarket',
  'yesterday': 'Yesterday',
  'salary': 'Salary',
  'gas': 'Gas',
  'accountLabel': 'Account',
  
  // Onboarding - General
  'startFreeTrial': '🚀 Start Free Trial',
  'skip': 'Skip',
  'later': 'Later',
  'finish': 'Finish',
  'complete': 'Complete',
  'allow': 'Allow',
  'authorize': 'Authorize',
  'configure': 'Configure',
  'setup': 'Setup',
  'tryNow': 'Try Now',
  'skipStep': 'Skip this step',
  'requiredField': 'Required',
  'start': 'Start',
  'begin': 'Begin',
  
  // Onboarding - Step Navigation
  'onboardingStepOf': 'of', // Used in "1 of 3" format
  'actionToComplete': 'action to complete',
  'actionsToComplete': 'actions to complete',
  'actionOn': 'Action', // Used in "Action 1 of 3" format
  
  // Onboarding - Basic Steps
  'save2HoursEveryDay': 'Save 2 Hours Every Day',
  'save2HoursDescription': 'Join 100,000+ users who doubled their productivity with Fast App',
  'averageUserSaves': 'Average user saves 14h/week',
  'everythingInOnePlace': 'Everything in One Place',
  'everythingInOnePlaceDescription': 'No more switching between apps. All your work, organized and accessible.',
  'trustedByFortune500': 'Trusted by Fortune 500',
  'thirtyDaysFreeNoCard': '30 Days Free, No Card',
  'thirtyDaysFreeDescription': 'Try everything free. Cancel anytime. Join thousands already saving time.',
  'secureAndPrivate': '100% Secure & Private',
  
  // Onboarding - Interactive Steps
  'welcomeToMusicAI': '🎵 Welcome to MusicAI!',
  'welcomeToMusicAIDescription': 'Ready to create hits with AI? Let\'s start with your artist name.',
  'tracksCreatedThisWeek': '500,000+ tracks created this week',
  'yourArtistName': 'Your artist name',
  'yourArtistNameSubtitle': 'How do you want to be credited on your creations?',
  'artistNamePlaceholder': 'Ex: DJ Phoenix, MC Flow...',
  'artistNameHelper': 'This will be your musical identity',
  'chooseArtistName': 'Choose your artist name',
  'letsGo': 'Let\'s go!',
  
  'stayConnectedToStudio': '🔥 Stay connected to the studio',
  'stayConnectedDescription': 'Get notifications when your tracks are ready and discover trends.',
  'realTimeNotifications': 'Real-time notifications on your creations',
  'creationNotifications': 'Creation notifications',
  'creationNotificationsSubtitle': 'Be notified when your tracks are generated',
  'creationNotificationsDescription': 'Get a notification as soon as a track is ready',
  'allowNotifications': 'Allow notifications',
  'allowNotificationsSubtitle': 'Enable notifications to not miss anything',
  'notificationPermissionRationale': 'To notify you when your creations are ready and share the latest musical trends.',
  
  'whatIsYourStyle': '🎧 What\'s your style?',
  'whatIsYourStyleDescription': 'Choose your favorite genres so the AI creates your unique sound.',
  'aiTrainedOnTracks': 'AI trained on 10M+ tracks',
  'yourMusicalGenres': 'Your musical genres',
  'yourMusicalGenresSubtitle': 'Select at least 2 styles you love',
  'chooseAtLeastTwoGenres': 'Choose at least 2 musical genres',
  'hipHopRap': 'Hip-Hop/Rap',
  'electroEDM': 'Electronic/EDM',
  'pop': 'Pop',
  'rockMetal': 'Rock/Metal',
  'rnbSoul': 'R&B/Soul',
  'afrobeat': 'Afrobeat',
  'darkStudioMode': 'Dark studio mode',
  'darkStudioModeSubtitle': 'Dark interface for your creative sessions',
  'darkStudioModeDescription': 'Perfect for composing in the mood',
  'perfect': 'Perfect!',
  
  'aiInAction': '🤖 AI in action',
  'aiInActionDescription': 'Discover the power of our music generator.',
  'generateTrackIn30Seconds': 'Generate a track in 30 seconds',
  'generateFirstTrack': 'Generate your first track',
  'generateFirstTrackSubtitle': 'Launch the AI and listen to the magic happen',
  'generateDemoDescription': 'Click to generate a Hip-Hop beat live with our AI',
  'skipDemo': 'Skip demo',
  
  'studioAlmostReady': '🎬 Your studio is almost ready',
  'studioAlmostReadyDescription': 'Final settings for an optimal creative experience!',
  'yourCreationsYourProperty': 'Your creations remain your property',
  'audioImprovement': 'Audio improvement',
  'audioImprovementSubtitle': 'Help us perfect the sound quality',
  'audioImprovementDescription': 'Anonymous data to optimize musical AI',
  'cloudBackup': 'Cloud backup',
  'cloudBackupSubtitle': 'Sync your creations across all your devices',
  'finishLater': 'Finish later',
  'launchMyStudio': 'Launch my studio! 🎵',
  
  // Interactive Actions
  'tryItNow': 'Try it now',
  'configureNow': 'Configure now',
  
  // Social Login
  'apple': 'Apple',
  'google': 'Google',
  
  // Form Validation
  'pleaseEnterEmail': 'Please enter an email address',
  'pleaseEnterValidEmail': 'Please enter a valid email address',
  'pleaseEnterPassword': 'Please enter a password',
  'passwordMin6Chars': 'Password must be at least 6 characters long',
  'passwordMustContainLettersNumbers': 'Password must contain both letters and numbers',
  'pleaseConfirmPassword': 'Please confirm your password',
  'passwordsDoNotMatch': 'Passwords do not match',
  'pleaseEnterName': 'Please enter your name',
  'nameMin2Chars': 'Name must be at least 2 characters long',
  'pleaseEnterPhoneNumber': 'Please enter a phone number',
  'pleaseEnterValidPhoneNumber': 'Please enter a valid phone number',
  
  // Errors
  'emailRequired': 'Email is required',
  'passwordRequired': 'Password is required',
  'invalidEmail': 'Please enter a valid email',
  'passwordTooShort': 'Password must be at least 6 characters',
  'networkError': 'Network error. Please try again.',
  'somethingWentWrong': 'Something went wrong',
  'unexpectedError': 'An unexpected error occurred. Please try again later.',
  
  // Validation
  'required': 'This field is required',
  'invalid': 'Invalid input',
  'tooShort': 'Too short',
  'tooLong': 'Too long',

  // Shared Widget Strings
  // Confirmation Dialog
  'confirm': 'Confirm',
  
  // Image Picker
  'selectImage': 'Select Image',
  'photoLibrary': 'Photo Library',
  'ok': 'OK',
  'notImplemented': 'Not Implemented',
  'addImagePickerDependency': 'Add image_picker dependency to pubspec.yaml to use this feature.',
  
  // Input Fields
  'search': 'Search',
  'enterPhoneNumber': 'Enter phone number',
  
  // Context Menu Actions
  'copy': 'Copy',
  'share': 'Share',
  
  // Forms
  'select': 'Select',

  // Supabase Error Messages
  'unexpectedErrorOccurred': 'An unexpected error has occurred. Please try again later.',
  'anonymousProviderDisabled': 'Anonymous connections are currently disabled.',
  'badCodeVerifier': 'An error occurred in the authentication process. Please try again.',
  'badJson': 'An error occurred while processing the request. Please try again.',
  'badJwt': 'Your session has expired. Please log in again.',
  'badOauthCallback': 'An error occurred with the OAuth process. Please try again.',
  'badOauthState': 'An error occurred with the OAuth process. Please try again.',
  'captchaFailed': 'Captcha verification failed. Please try again.',
  'conflict': 'There was a conflict with your request. Please try again later.',
  'emailAddressNotAuthorized': 'This email address is not authorized.',
  'emailConflictIdentityNotDeletable': 'This email is associated with another account and cannot be deleted.',
  'emailExists': 'An account with this email already exists.',
  'emailNotConfirmed': 'Please confirm your email address before signing in.',
  'emailProviderDisabled': 'Email and password registrations are currently disabled.',
  'flowStateExpired': 'The authentication process has expired. Please try to log in again.',
  'flowStateNotFound': 'The authentication process has expired. Please try to log in again.',
  'hookPayloadOverSizeLimit': 'An internal server error occurred. Please try again later.',
  'hookTimeout': 'An internal server error occurred. Please try again later.',
  'hookTimeoutAfterRetry': 'An internal server error occurred. Please try again later.',
  'identityAlreadyExists': 'This identity is already linked to an account.',
  'identityNotFound': 'The requested identity was not found.',
  'insufficientAal': 'Additional authentication is required. Please complete the MFA challenge.',
  'inviteNotFound': 'The invitation has expired or has already been used.',
  'invalidCredentials': 'Invalid login credentials. Please check and try again.',
  'manualLinkingDisabled': 'Manual account linking is not enabled.',
  'mfaChallengeExpired': 'The MFA challenge has expired. Please request a new one.',
  'mfaFactorNameConflict': 'An MFA factor with this name already exists.',
  'mfaFactorNotFound': 'The requested MFA factor was not found.',
  'mfaIpAddressMismatch': 'MFA enrollment must be done from the same IP address.',
  'mfaVerificationFailed': 'MFA verification failed. Please try again.',
  'mfaVerificationRejected': 'MFA verification was rejected.',
  'mfaVerifiedFactorExists': 'A verified phone factor already exists for this user.',
  'mfaTotpEnrollDisabled': 'MFA TOTP enrollment is currently disabled.',
  'mfaTotpVerifyDisabled': 'MFA TOTP verification is currently disabled.',
  'mfaPhoneEnrollDisabled': 'MFA phone enrollment is currently disabled.',
  'mfaPhoneVerifyDisabled': 'MFA phone verification is currently disabled.',
  'noAuthorization': 'You are not authorized to perform this action.',
  'notAdmin': 'This action requires administrator privileges.',
  'oauthProviderNotSupported': 'This OAuth provider is not supported.',
  'otpDisabled': 'One-time password login is currently disabled.',
  'otpExpired': 'The OTP code has expired or is invalid. Please request a new one.',
  'overEmailSendRateLimit': 'Too many emails have been sent. Please try again later.',
  'overRequestRateLimit': 'Too many requests. Please try again in a few minutes.',
  'overSmsSendRateLimit': 'Too many SMS messages have been sent. Please try again later.',
  'phoneExists': 'An account with this phone number already exists.',
  'phoneNotConfirmed': 'Please confirm your phone number before signing in.',
  'phoneProviderDisabled': 'Phone number registrations are currently disabled.',
  'providerDisabled': 'This authentication provider is currently disabled.',
  'providerEmailNeedsVerification': 'Please verify your email address to complete the sign-in process.',
  'reauthenticationNeeded': 'Please reauthenticate to change your password.',
  'reauthenticationNotValid': 'Reauthentication failed. Please try again.',
  'requestTimeout': 'The request timed out. Please try again.',
  'samePassword': 'Your new password must be different from your current password.',
  'samlError': 'An error occurred with the SAML authentication process. Please contact support.',
  'sessionNotFound': 'Your session has expired. Please log in again.',
  'signupDisabled': 'New account creation is currently disabled.',
  'singleIdentityNotDeletable': 'You cannot delete your only identity.',
  'smsSendFailed': 'Failed to send SMS. Please try again later.',
  'ssoDomainAlreadyExists': 'This SSO domain is already registered.',
  'ssoProviderNotFound': 'The SSO provider was not found.',
  'tooManyEnrolledMfaFactors': 'You have reached the maximum number of enrolled MFA factors.',
  'unexpectedAudience': 'An error occurred in the authentication process. Please try again.',
  'unexpectedFailure': 'An unexpected error occurred. Please try again later.',
  'userAlreadyExists': 'A user with this information already exists.',
  'userBanned': 'This account has been temporarily banned. Please try again later.',
  'userNotFound': 'User not found.',
  'userSsoManaged': 'This user account is managed by SSO and cannot be updated.',
  'validationFailed': 'The provided information is invalid. Please check and try again.',
  'weakPassword': 'The password does not meet security requirements. Please choose a stronger password.',
  'authenticationError': 'An authentication error occurred. Please try again.',
  'duplicateRecord': 'A record with this information already exists.',
  'foreignKeyViolation': 'This action cannot be performed due to related data constraints.',
  'resourceNotFound': 'The requested resource does not exist.',
  'insufficientPermissions': 'You do not have permission to perform this action.',
  'databaseError': 'A database error occurred. Please try again later.',
};
